---
# tasks file for ansible-netbox
- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: install.yml

- include: tags.yml

- include: tenant_groups.yml

- include: tenants.yml

- include: sites.yml
